final Map<String, List<String>> keralaPlaces = {
  "Thiruvananthapuram": [
    "Thiruvananthapuram",
    "Neyyattinkara",
    "Nedumangad",
    "Varkala",
    "Chirayinkeezhu",
    "Kattakada",
  ],
  "Kollam": [
    "Kollam",
    "Karunagappally",
    "Kunnathoor",
    "Kottarakkara",
    "Punalur",
    "Pathanapuram",
  ],
  "Pathanamthitta": [
    "Adoor",
    "Konni",
    "Kozhencherry",
    "Mallappally",
    "Ranni",
    "Thiruvalla",
  ],
  "Alappuzha": [
    "Alappuzha",
    "Ambalappuzha",
    "Cherthala",
    "Chengannur",
    "Karthikappally",
    "Mavelikkara",
  ],
  "Kottayam": [
    "Kottayam",
    "Changanassery",
    "Kanjirappally",
    "Meenachil",
    "Vaikom",
  ],
  "Idukki": [
    "Idukki",
    "Devikulam",
    "Peermade",
    "Udumbanchola",
    "Thodupuzha",
    "Adimali",
    "Nedumkandam",
    "Kattappana",
  ],
  "Ernakulam": [
    "Kanayannur",
    "Kochi",
    "Kunnathunad",
    "Aluva",
    "Paravur",
    "Muvattupuzha",
    "Kothamangalam",
  ],
  "Thrissur": [
    "Thrissur",
    "Chavakkad",
    "Kodungallur",
    "Mukundapuram",
    "Talappilly",
  ],
  "Palakkad": [
    "Palakkad",
    "Alathur",
    "Chittur",
    "Mannarkkad",
    "Ottapalam",
    "Pattambi",
  ],
  "Malappuram": [
    "Ernad",
    "Perinthalmanna",
    "Nilambur",
    "Tirur",
    "Tirurangadi",
    "Kondotty",
    "Ponnani",
  ],
  "Kozhikode": ["Kozhikode", "Vatakara", "Koyilandy", "Thamarassery"],
  "Wayanad": ["Vythiri", "Mananthavady", "Sulthan Bathery"],
  "Kannur": ["Kannur", "Thalassery", "Iritty", "Payyannur", "Taliparamba"],
  "Kasaragod": ["Kasaragod", "Manjeshwaram", "Vellarikundu", "Hosdurg"],
};
